version: '2'

services:
    mysql:
      container_name: mysql-test
      image: mysql/mysql-server:5.6
      ports:
        - "3306:3306"
      env_file: .env
      volumes:
        - db:/var/lib/mysql

volumes:
    db:
      driver: local
